### PR TITLE
Feature: Added Input select input with a search box

### PR DESCRIPTION
**Pull request by firoz3130**
### Description:
This pull request addresses issue #13 , where we have to modify the existing UI for select component. The component should contain a search/filtering option.
The current setup is like this.
image

### Changes Made:
- Implemented modifications to the select component .
Achieved output
image

### Testing:
- Tested the solution extensively in both development and production environments to ensure functionality and stability.
- Verified that search/filter  actions  inside the select componentnow work as expected .

### How to Test:
1. Deploy the latest changes to the production environment.
2. Visit https://www.menteor.space/join-waiting-list
3.  Tap on the select component under the question "How you came to know about Menteor?"
4.  Search for the required platform.

### Screenshots:

image

### Checklist:
- [x] Implemented solution to fix the issue.
- [x] Tested changes thoroughly in both development and production environments.
- [x] Verified that server actions work as expected in production.
- [x] Documented the testing process and provided instructions for testing the changes.

### CODE REVIEW

**Comment by Ahd-Kabeer-Hadi** [comment]
@firoz3130 good work man, but have you checked it responsiveness? and color schemes?

**Comment by firoz3130** [comment]
> @firoz3130 good work man, but have you checked it's responsiveness,color schemes and font styles?

The color schemes in the sense that green layout that should come on the outer layer of the options  right>?

**Comment by Ahd-Kabeer-Hadi** [comment]
> > @firoz3130 good work man, but have you checked it's responsiveness,color schemes and font styles?
> 
> The color schemes in the sense that green layout that should come on the outer layer of the options right>?

yes, it should practically in sync with other elements

**Comment by Ahd-Kabeer-Hadi** [comment]
@firoz3130 I'm closing this PR due to inactivity since it been days and i couldn't find any updates on review so far

**Pull request closed without merging**
